#!/usr/bin/env python3
"""
Analysis Report Generator

Formats analysis findings into structured markdown reports with diff suggestions.
Used by the agent after completing trace analysis.

USAGE:
    python report_generator.py \
        --symptom "output missing expected data" \
        --category data_gap \
        --trace-id abc123 \
        --root-cause "API endpoint not called" \
        --evidence "Tool calls: api_v1 (1), api_v2 (0)"

OUTPUT:
    Structured markdown report to stdout
"""

import argparse
import sys
from datetime import datetime
from typing import Optional, List


def generate_report(
    symptom: str,
    category: str,
    trace_id: str,
    root_cause: str,
    project: Optional[str] = None,
    evidence: Optional[str] = None,
    fixes: Optional[List[str]] = None,
) -> str:
    """Generate a structured analysis report."""

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Category display names (generic categories)
    category_names = {
        "data_gap": "Data Gap (Missing Data)",
        "output_error": "Output Error (Incorrect Result)",
        "execution_error": "Execution Error",
        "latency": "Performance/Latency",
        "quality_issue": "Quality Issue",
        "cost": "Cost Optimization",
    }

    category_display = category_names.get(category, category)

    report = f"""# Trace Analysis Report

**Generated:** {timestamp}

---

## Symptom

> {symptom}

| Field | Value |
|-------|-------|
| **Trace ID** | `{trace_id}` |
| **Category** | {category_display} |
"""

    if project:
        report += f"| **Project** | {project} |\n"

    report += f"""
---

## Root Cause

{root_cause}

---

## Evidence

"""

    if evidence:
        report += f"""{evidence}

---

"""
    else:
        report += """*No evidence provided. Add with --evidence flag.*

---

"""

    report += """## Recommended Fixes

"""

    if fixes:
        for i, fix in enumerate(fixes, 1):
            report += f"""### Fix {i}

{fix}

"""
    else:
        report += """*No specific fixes provided. Add with --fix flag (can be used multiple times).*

---

## Verification Steps

After applying fixes:

1. Re-run your workflow with the same inputs

2. Retrieve new trace:
   ```bash
   python3 trace_retriever.py --last 1 --mode io
   ```

3. Verify the issue is resolved

"""

    report += """---

*Report generated by langfuse-analyzer plugin*
"""

    return report


def generate_diff_suggestion(
    file_path: str,
    description: str,
    before_lines: List[str],
    after_lines: List[str],
    context_before: int = 1,
) -> str:
    """Generate a diff-style fix suggestion."""

    diff = f"""**File:** `{file_path}`

**Change:** {description}

```diff
"""

    # Add context lines (unchanged)
    for line in before_lines[:context_before]:
        diff += f" {line}\n"

    # Add removed lines
    for line in before_lines[context_before:]:
        diff += f"-{line}\n"

    # Add added lines
    for line in after_lines:
        diff += f"+{line}\n"

    diff += "```\n"

    return diff


def main():
    parser = argparse.ArgumentParser(
        description="Generate structured analysis reports",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "--symptom",
        required=True,
        help="User's original problem description"
    )
    parser.add_argument(
        "--category",
        required=True,
        choices=[
            "data_gap", "output_error", "execution_error",
            "latency", "quality_issue", "cost"
        ],
        help="Classified symptom category"
    )
    parser.add_argument(
        "--trace-id",
        required=True,
        help="Langfuse trace ID"
    )
    parser.add_argument(
        "--project",
        help="Optional project context for the report"
    )
    parser.add_argument(
        "--root-cause",
        required=True,
        help="Identified root cause explanation"
    )
    parser.add_argument(
        "--evidence",
        help="Evidence supporting the root cause (markdown formatted)"
    )
    parser.add_argument(
        "--fix",
        action="append",
        dest="fixes",
        help="Recommended fix (can be used multiple times)"
    )

    args = parser.parse_args()

    report = generate_report(
        symptom=args.symptom,
        category=args.category,
        trace_id=args.trace_id,
        root_cause=args.root_cause,
        project=args.project,
        evidence=args.evidence,
        fixes=args.fixes,
    )

    print(report)


if __name__ == "__main__":
    main()
